import "jspdf-autotable";
import autoTable from "jspdf-autotable";

import { PdfEngine } from "@/components/pdf-layout-design/PdfEngine";
import { pdfTemplateService } from "@/components/pdf-layout-design/services/pdf-template";
import { PAPER_SIZES } from "@/components/pdf-layout-design/constants";

import type { TacticalSkuKpis, TacticalSkuProductRow } from "../types";
import { formatNumber, formatPercent } from "./format";

type CompanyData = Record<string, unknown>;

type TacticalSkuPrintPayload = {
  month: string;
  rows: TacticalSkuProductRow[];
  kpis: TacticalSkuKpis;
  generatedBy?: string;
};

async function fetchCompanyData(): Promise<CompanyData | null> {
  try {
    const res = await fetch("/api/pdf/company", { credentials: "include" });
    if (!res.ok) return null;
    const result = (await res.json()) as { data?: CompanyData[] | CompanyData };
    if (Array.isArray(result.data)) return result.data[0] ?? null;
    return result.data ?? null;
  } catch {
    return null;
  }
}

function formatDateTime(value: Date): string {
  return value.toLocaleString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function formatReportMonth(month: string): string {
  if (!/^\d{4}-\d{2}$/.test(month)) return month || "-";
  const [year, mm] = month.split("-");
  const monthIndex = Number(mm) - 1;
  if (monthIndex < 0 || monthIndex > 11) return month;

  const date = new Date(Number(year), monthIndex, 1);
  return date.toLocaleString("en-US", { month: "long", year: "numeric" });
}

function safeFilePart(value: string): string {
  return value.replace(/[\\/:*?"<>|]+/g, "-").trim();
}

function readTemplateName(templates: Array<{ name: string }>): string {
  return (
    templates.find((t) => t.name === "Header")?.name ||
    templates[0]?.name ||
    "Tactical SKU Printables"
  );
}

export async function printTacticalSkuReport(params: TacticalSkuPrintPayload): Promise<void> {
  const { month, rows, kpis, generatedBy } = params;
  const printableMonth = formatReportMonth(month);

  const now = new Date();
  const dateStr = formatDateTime(now);
  const fileName = `Tactical_SKU_${safeFilePart(month || "report")}_${now
    .toISOString()
    .slice(0, 10)}.pdf`;

  const [companyData, templates] = await Promise.all([
    fetchCompanyData(),
    pdfTemplateService.fetchTemplates(),
  ]);

  const templateName = readTemplateName(templates);

  const topSalesman = rows
    .flatMap((row) => row.salesmen)
    .sort((a, b) => b.reach - a.reach)[0];

  const tableRows = rows.map((row) => [
    String(row.rank),
    row.brand || "-",
    row.category || "-",
    row.productName || "-",
    formatNumber(row.inventory),
    formatNumber(row.totalReach),
    formatNumber(row.target),
    formatPercent(row.targetPercent),
  ]);

  const doc = await PdfEngine.generateWithFrame(templateName, companyData, (pdf, startY, config) => {
    const margins = config.margins || { top: 10, bottom: 10, left: 10, right: 10 };
    const pageW = pdf.internal.pageSize.getWidth();
    const usableW = pageW - margins.left - margins.right;

    const baseSize =
      config.paperSize === "Custom"
        ? config.customSize
        : PAPER_SIZES[config.paperSize] || PAPER_SIZES.A4;
    const paperHeight = config.orientation === "landscape" ? baseSize.width : baseSize.height;
    const bottomMargin = config.bodyEnd ? paperHeight - config.bodyEnd : margins.bottom;

    let y = startY;

    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(13);
    pdf.setTextColor(20, 20, 20);
    pdf.text("Tactical SKU Printables", margins.left, y, { baseline: "top" });

    y += 7;
    pdf.setFontSize(10.5);
    pdf.text("Salesman Product Performance", margins.left, y, { baseline: "top" });

    y += 8;
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(80, 80, 80);

    const leftX = margins.left;
    const rightX = margins.left + usableW * 0.52;
    const lineH = 5;

    pdf.text(`Report Month: ${printableMonth || "-"}`, leftX, y, { baseline: "top" });
    pdf.text(`Top Salesman: ${topSalesman?.salesmanName || "N/A"}`, rightX, y, { baseline: "top" });
    y += lineH;

    pdf.text(`Total Products: ${formatNumber(kpis.totalProducts)}`, leftX, y, { baseline: "top" });
    pdf.text(`Top Salesman Code: ${topSalesman?.code || "N/A"}`, rightX, y, { baseline: "top" });
    y += lineH;

    pdf.text(`Date: ${dateStr}`, leftX, y, { baseline: "top" });
    pdf.text(`Generated By: ${generatedBy || "User"}`, rightX, y, { baseline: "top" });

    y += 7;
    pdf.setTextColor(20, 20, 20);
    pdf.setFont("helvetica", "bold");
    pdf.setFontSize(8.5);
    pdf.text(`Total Records: ${rows.length}`, margins.left, y, { baseline: "top" });
    pdf.setFont("helvetica", "normal");

    y += 6;
    pdf.setFontSize(8.2);
    pdf.setTextColor(60, 60, 60);
    pdf.text(
      `Inventory: ${formatNumber(kpis.totalInventory)}   Reach: ${formatNumber(kpis.totalReach)}   Target: ${formatNumber(kpis.totalTarget)}   Attainment: ${formatPercent(kpis.overallPercent)}`,
      margins.left,
      y,
      { baseline: "top" },
    );

    const colNo = 12;
    const colBrand = 20;
    const colCategory = 23;
    const colProduct = 50;
    const colInventory = 20;
    const colReach = 19;
    const colTarget = 19;
    const colPercent = usableW - colNo - colBrand - colCategory - colProduct - colInventory - colReach - colTarget;

    autoTable(pdf, {
      startY: y + 6,
      margin: { ...margins, bottom: bottomMargin },
      tableWidth: usableW,
      tableLineWidth: 0.2,
      tableLineColor: [0, 0, 0],
      head: [["No.", "Brand", "Category", "Product Name", "Inventory", "Reach", "Target", "Target %"]],
      body: tableRows.length ? tableRows : [["-", "-", "-", "No data", "0", "0", "0", "0.00%"]],
      theme: "striped",
      styles: {
        lineWidth: 0.1,
        lineColor: [0, 0, 0],
      },
      headStyles: {
        fillColor: [41, 128, 185],
        textColor: 255,
        fontSize: 8,
        fontStyle: "bold",
        halign: "left",
        valign: "middle",
        cellPadding: 1.6,
        lineWidth: 0.1,
        lineColor: [0, 0, 0],
      },
      bodyStyles: {
        fontSize: 7.5,
        valign: "top",
        cellPadding: 1.6,
        lineWidth: 0.1,
        lineColor: [0, 0, 0],
      },
      alternateRowStyles: { fillColor: [245, 245, 245] },
      columnStyles: {
        0: { cellWidth: colNo, halign: "center" },
        1: { cellWidth: colBrand },
        2: { cellWidth: colCategory },
        3: { cellWidth: colProduct },
        4: { cellWidth: colInventory, halign: "right" },
        5: { cellWidth: colReach, halign: "right" },
        6: { cellWidth: colTarget, halign: "right" },
        7: { cellWidth: colPercent, halign: "right" },
      },
    });

    const lastTableY = (pdf as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable
      ?.finalY;
    let notesY = (lastTableY ?? y + 24) + 10;
    const pageH = pdf.internal.pageSize.getHeight();
    const notesBlockH = 10;
    const maxY = pageH - bottomMargin;

    if (notesY + notesBlockH > maxY) {
      pdf.addPage();
      notesY = margins.top;
    }

    pdf.setDrawColor(0, 0, 0);
    pdf.setLineWidth(0.2);
    const lineStartX = margins.left;
    const lineEndX = margins.left + usableW;
    pdf.line(lineStartX, notesY, lineEndX, notesY);
  });

  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
